server:
  port: 8001
spring:
  application:
    name: cloud-payment-service  #定义服务名称
  datasource:  #配置连接数据库的信息
    username: root
    password: 123
    url: jdbc:mysql://localhost/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml #指定访问mapper映射文件的位置
  type-aliases-package: com.yousian.pojo  # 所有Entity 别名类所在包
eureka:
  client:
    # 注册进 Eureka 的服务中心
    register-with-eureka: true
    # 检索 服务中心 的其它服务
    fetch-registry: true
    service-url:
      # 设置与 Eureka Server 交互的地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #Eureka分客户端向服务端发送心跳的时间间隔 单位为秒30秒
    lease-renewal-interval-in-seconds: 1
    #Eureka服务短向服务端发送心眺最后一次等待时间上线 默认90秒
    lease-expiration-duration-in-seconds: 2