server:
  port: 8004
spring:
  application:
    name: cloud-provider-service
  datasource:  #配置连接数据库的信息
    username: root
    password: 123
    url: jdbc:mysql://localhost/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181  #注册到zookeeper中心的地址
mybatis:
  mapper-locations: classpath:mapper/*.xml #指定访问mapper映射文件的位置
  type-aliases-package: com.yousian.pojo   # 所有Entity 别名类所在包
