server:
  port: 82
spring:
  application:
    name: cloud-customer-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}