server:
  port: 8006
spring:
  application:
    name: consul-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
  cloud:
    consul:  #consul注册中心的地址
      host: localhost
      port: 8500
      discovery:    # 指定注册对外暴露的服务名称
        service-name: ${spring.application.name}
mybatis:
  mapper-locations: classpath:mapper/*.xml #指定访问mapper映射文件的位置
  type-aliases-package: com.yousian.pojo    # 所有Entity 别名类所在包
